language: python
before_script:
  - apt-get update
  - sudo apt-get install libopenmpi-dev

install:
  - pip install -r requirements.txt

script:
  - pip install .
  - python nnpotential/tests/import_all.py
