language: python
before_script:
  - sudo apt-get -qq update
  - sudo apt-get install libopenmpi-dev
env:
  - C_INCLUDE_PATH=${C_INCLUDE_PATH}:/usr/include/openmpi:/usr/lib/openmpi/include
  - LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/lib/openmpi:/usr/lib_x86_64
install:
  - pip install -r requirements.txt

script:
  - pip install .
  - python nnpotential/tests/import_all.py
