language: python
before_script:
  - sudo apt-get -qq update
  - sudo apt-get install mpich2

install:
  - pip install -r requirements.txt

script:
  - pip install .
  - python nnpotential/tests/import_all.py
