language: python

install:
  - sudo apt-get -qq update
  - sudo apt-get install libopenmpi-de
  - pip install -r requirements.txt

script:
  - pip install .
  - python nnpotential/tests/import_all.py
